# tools/release.ps1 -- build a "directly publishable" release package.
#
# Why this exists:
#   This workspace has NO git, and `upload/` is a STALE hand-made copy
#   (root gosim/ has 90 .go files; upload/gosim/ only has 55). Hand-maintained
#   copies always diverge, so the release artifact is now GENERATED by this script
#   instead of being synced by hand.
#
# Release boundary (same as .gitignore):
#   include = README.md + gosim/ + docs/(with verdict) + tools/ + MingChinese.ttf
#   exclude = out/ (internal evidence + caches) + upload/ (stale copy) + build artifacts
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File D:\Code\YehenalaMarket\tools\release.ps1
#   ... -Version 1.0.0        # set the version tag
#   ... -OutDir D:\dist       # set the output directory
#   ... -SkipTests            # skip build/vet/test
#
# The script does NOT modify the workspace (read-only + writes under -OutDir).
# Exit code: 0 = ok, 1 = failed.
#
# NOTE: this file is deliberately ASCII-ONLY. Windows PowerShell 5.1 reads .ps1 files
# as ANSI unless they carry a UTF-8 BOM; non-ASCII here would break parsing. The Chinese
# release notes live in tools\RELEASE-MANIFEST.template.md (UTF-8) and are appended here.

param(
    [string]$Version = '1.0.0-2026-09-20',
    [string]$OutDir  = '',
    [switch]$SkipTests
)

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
if ([string]::IsNullOrWhiteSpace($OutDir)) {
    $OutDir = Join-Path (Split-Path -Parent $root) 'dist'
}
$pkg = Join-Path $OutDir ("YehenalaMarket-$Version")

Write-Host "== release build ==" -ForegroundColor Cyan
Write-Host ("workspace : {0}" -f $root)
Write-Host ("version   : {0}" -f $Version)
Write-Host ("output    : {0}" -f $pkg)
Write-Host ''

# ---- 1) optional: run tests first so we never ship a broken tree ----
if (-not $SkipTests) {
    $go = 'D:\Code\Go\bin\go.exe'
    if (Test-Path $go) {
        $gomod = Join-Path $root 'gosim'
        Write-Host '-- go build / vet / test --' -ForegroundColor Cyan
        Push-Location $gomod
        try {
            & $go build ./... ; if ($LASTEXITCODE -ne 0) { throw 'go build failed' }
            & $go vet   ./... ; if ($LASTEXITCODE -ne 0) { throw 'go vet failed' }
            & $go test  ./... -count=1 | Out-Null
            if ($LASTEXITCODE -ne 0) { throw 'go test failed' }
            Write-Host 'build / vet / test all passed' -ForegroundColor Green
        } finally { Pop-Location }
    } else {
        Write-Host ("skipping tests: {0} not found" -f $go) -ForegroundColor Yellow
    }
}

# ---- 2) assemble the release tree ----
if (Test-Path $pkg) { Remove-Item $pkg -Recurse -Force }
New-Item -ItemType Directory -Force -Path $pkg | Out-Null

$readme = Join-Path $root 'README.md'
if (Test-Path $readme) { Copy-Item $readme (Join-Path $pkg 'README.md') -Force }
$font = Join-Path $root 'MingChinese.ttf'
if (Test-Path $font) { Copy-Item $font (Join-Path $pkg 'MingChinese.ttf') -Force }

foreach ($d in @('gosim', 'tools')) {
    $s = Join-Path $root $d
    if (Test-Path $s) { Copy-Item $s (Join-Path $pkg $d) -Recurse -Force }
}

# docs/: markdown + html only, plus docs/verdict/ and docs/archive/
$docsSrc = Join-Path $root 'docs'
$docsDst = Join-Path $pkg 'docs'
New-Item -ItemType Directory -Force -Path $docsDst | Out-Null
Get-ChildItem $docsSrc -File |
    Where-Object { $_.Extension -in '.md', '.html' } |
    ForEach-Object { Copy-Item $_.FullName $docsDst -Force }
foreach ($sub in @('verdict', 'archive')) {
    $sd = Join-Path $docsSrc $sub
    if (-not (Test-Path $sd)) { continue }
    $dd = Join-Path $docsDst $sub
    New-Item -ItemType Directory -Force -Path $dd | Out-Null
    Get-ChildItem $sd -File |
        Where-Object { $_.Extension -in '.md', '.html' } |
        ForEach-Object { Copy-Item $_.FullName $dd -Force }
}

# ---- 3) strip anything that must not ship ----
foreach ($junk in @('out', 'upload', 'node_modules', '.git')) {
    $p = Join-Path $pkg $junk
    if (Test-Path $p) { Remove-Item $p -Recurse -Force }
}
Get-ChildItem $pkg -Recurse -File -Include *.exe, *.test -ErrorAction SilentlyContinue |
    Remove-Item -Force -ErrorAction SilentlyContinue

# ---- 4) release notes: header (ASCII, generated) + Chinese template (UTF-8) ----
$goMod = Join-Path $pkg 'gosim\go.mod'
$goVer = '(none)'
if (Test-Path $goMod) {
    $line = Select-String -Path $goMod -Pattern '^go ' | Select-Object -First 1
    if ($line) { $goVer = $line.Line.Trim() }
}
$files = Get-ChildItem $pkg -Recurse -File
$sizeMB = [math]::Round((($files | Measure-Object Length -Sum).Sum / 1MB), 2)

$header = @(
    "<!-- generated by tools/release.ps1 -->",
    "",
    "| field | value |",
    "|---|---|",
    "| version | $Version |",
    "| built | $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') |",
    "| files | $($files.Count) |",
    "| size | $sizeMB MB |",
    "| go module | $goVer |",
    "",
    "---",
    ""
)
$out = Join-Path $pkg 'RELEASE-MANIFEST.md'
$header | Out-File $out -Encoding utf8
$tpl = Join-Path $root 'tools\RELEASE-MANIFEST.template.md'
if (Test-Path $tpl) {
    Get-Content $tpl -Encoding UTF8 | Out-File $out -Encoding utf8 -Append
}

# ---- 5) zip ----
$zip = "$pkg.zip"
if (Test-Path $zip) { Remove-Item $zip -Force }
Compress-Archive -Path (Join-Path $pkg '*') -DestinationPath $zip

Write-Host ''
Write-Host ("package dir : {0}" -f $pkg) -ForegroundColor Green
Write-Host ("zip         : {0}  ({1} MB)" -f $zip, [math]::Round((Get-Item $zip).Length/1MB,2)) -ForegroundColor Green
Write-Host ("files       : {0}" -f $files.Count)
exit 0
